title:               "ICTP SAIFR CSSM"
url:                 http://ictp-saifr-cssm.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle','vendor']

collections:
  past:
    output: true
    title: Previous seminar
    directory: ./_past

  upcoming:
    output: true
    title: Upcoming seminars
    directory: ./_upcoming

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              "ICTP SAIFR CSSM"
  url:               http://ictp-saifr-cssm.github.io
  email:             ictp.saifr.seminais@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
